In [1]:
import numpy as np

In [2]:
# From list
a = np.array([1, 2, 3])
print(a)

# Multi-dimensional
b = np.array([[1, 2], [3, 4]])
print(b)

# Zeros and Ones
np.zeros((2, 3))
np.ones((3, 3))

# Identity matrix
np.eye(4)

# arange and linspace
np.arange(0, 10, 2)       # [0,2,4,6,8]
np.linspace(0, 1, 5)      # 5 equally spaced numbers


[1 2 3]
[[1 2]
 [3 4]]


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# Array Attributes

In [4]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.ndim)     # 2
print(arr.shape)    # (2,3)
print(arr.size)     # 6
print(arr.dtype)    # int64


2
(2, 3)
6
int64


# Indexing & Slicing

In [3]:
a = np.arange(10)  # 0 to 9
print(a[0], a[-1])  # 0 9
print(a[2:7:2])     # slicing [2,4,6]

b = np.array([[10,20,30],[40,50,60]])
print(b[0,1])   # 20
print(b[:,1])   # column 1
print(b[1,:])   # row 1


0 9
[2 4 6]
20
[20 50]
[40 50 60]


In [5]:
a = np.array([1,2,3], dtype=np.float32)
print(a.dtype)  # float32

b = a.astype(np.int32)


float32


In [6]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

print(x + y)     # [11 22 33]
print(x * y)     # [10 40 90]
print(y / x)     # [10. 10. 10.]


[11 22 33]
[10 40 90]
[10. 10. 10.]


# Universal Functions (ufuncs)

Built-in vectorized operations.

In [7]:
a = np.arange(1, 6)
print(np.sqrt(a))
print(np.exp(a))
print(np.log(a))
print(np.sin(a))


[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


# Broadcasting

Allows operations between different shaped arrays

In [8]:
A = np.array([[1],[2],[3]])  # shape (3,1)
B = np.array([10,20,30])     # shape (3,)
print(A + B)


[[11 21 31]
 [12 22 32]
 [13 23 33]]


# Shape Manipulation
 Reshaping

In [9]:
arr = np.arange(12)
print(arr.reshape(3,4))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Flatten vs Ravel

In [10]:
a = np.arange(6).reshape(2,3)
b = a.flatten()   # copy
c = a.ravel()     # view

# Stacking & Splitting

In [12]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])

print(np.vstack((a,b)))
print(np.hstack((a,b.T)))

# Splitting
x = np.arange(9).reshape(3,3)
np.hsplit(x, 3)
np.vsplit(x, 3)


[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

## Math & Statistics

In [13]:
x = np.array([1,2,3,4])
print(x.sum(), x.mean(), x.std(), x.var())
print(x.min(), x.max())

10 2.5 1.118033988749895 1.25
1 4


In [24]:
arr = np.array([40,50,60])
print(arr[:,1])

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

### arr[:, 1] uses two indices:  arr[rows , columns]

In [25]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60]])

print(arr[:, 1])

[20 50]


In [22]:
arr = np.array([1,2,3,4,5])
arr[1:4]=0
print(arr)

[1 0 0 0 5]


# Axis

In [14]:
m = np.array([[1,2,3],[4,5,6]])
print(m.sum(axis=0))  # column-wise
print(m.sum(axis=1))  # row-wise


[5 7 9]
[ 6 15]


# Sorting & Searching

In [15]:
arr = np.array([3,1,2])
print(np.sort(arr))
print(np.argsort(arr))  # indices

m = np.array([[3,7],[9,1]])
print(np.sort(m, axis=0))


[1 2 3]
[1 2 0]
[[3 1]
 [9 7]]


## Linear Algebra

In [16]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(A @ B)             # matrix multiplication
print(np.dot(A,B))

print(np.transpose(A))
print(np.linalg.inv(A))
print(np.linalg.det(A))

# Eigenvalues
vals, vecs = np.linalg.eig(A)
print(vals, vecs)

# Solving Ax = b
b = np.array([1,2])
x = np.linalg.solve(A, b)


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
[-0.37228132  5.37228132] [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


### np.vectorize

In [17]:
def myfunc(x): return x**2 + 1
vfunc = np.vectorize(myfunc)
print(vfunc(np.arange(5)))


[ 1  2  5 10 17]


### np.fromfunction, np.fromiter

In [18]:
a = np.fromfunction(lambda i,j: i+j, (3,3), dtype=int)
print(a)

b = np.fromiter((i*i for i in range(5)), dtype=int)


[[0 1 2]
 [1 2 3]
 [2 3 4]]
